name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show git status and recent commits (diagnostic)
        run: |
          echo "--- git status ---"
          git --version || true
          git status --porcelain || true
          echo "--- recent commits ---"
          git --no-pager log -n 5 --oneline || true

      - name: List repository files (diagnostic)
        run: |
          echo "--- ls -la root ---"
          ls -la . || true
          echo "--- find top-level (depth 2) ---"
          find . -maxdepth 2 -type f | sed -n '1,200p' || true

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          allow_empty_commit: false
